apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: chalupa-bot-config-repo
  namespace: flux-system
spec:
  interval: 1m
  url: ssh://git@github.com/dodbham-gitops/dodbham-app-config
  secretRef:
    name: git-clone
  ref:
    branch: main
  spec:
    ignore: |
      # exclude all
      /*
      # include flux-resources and staging
      !/flux-resources
      !/staging
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: chalupa-bot-config-resources
  namespace: flux-system
spec:
  interval: 1m
  path: "./flux-resources"
  prune: true
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: chalupa-bot-config-repo
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: chalupa-bot-staging
  namespace: flux-system
spec:
  interval: 1m
  path: "./staging"
  prune: true
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: chalupa-bot-config-repo
    namespace: flux-system
