apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: chalupa-bot-app-config-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/dodbham-gitops/chalupa-bot-app-config
  secretRef:
    name: git-clone
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include flux-resources and staging
    !/flux-resources
    !/staging
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: chalupa-bot-app-config-resources
  namespace: flux-system
spec:
  interval: 1m
  path: "./flux-resources"
  prune: true
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: chalupa-bot-app-config-repo
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: chalupa-bot-staging
  namespace: flux-system
spec:
  interval: 1m
  path: "./staging"
  prune: true
  targetNamespace: flux-system
  sourceRef:
    kind: GitRepository
    name: chalupa-bot-config-repo
    namespace: flux-system
