apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-stage-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system 
  path: ./clusters/cluster-staging/secrets
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
