apiVersion: v1
data:
    DISCORD_TOKEN: ENC[AES256_GCM,data:qzaq62yAs8HMDHSCbAzXqxSKGMQC1OWUkVuGtN3WG+JhIOPLi9j6d6T5VVkrvG3v4xXS7NB/ecd7sblUfNfuprMl7BGSQOgFo3w3ahHGmfQ=,iv:g/7DaH53DIs/xUNYqoMpb+98G5ANI10QteoC7FVe5bs=,tag:qHXpGOndOGHlOo8e6KoPaA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: discord-token
    namespace: chalupa-bot-staging
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-04-16T22:10:02Z"
    mac: ENC[AES256_GCM,data:aX8YNWIn/PL/rDc7asHH1lw4AEnUvLeTFfT1u+bLeBmot8WomrfSA5iSJZPQMPZxEzdK3CaiTRyCIGcHMJE5mzF/G9/iwJDrsHueoQVLPwYB6x/30mFzLzJXtL3RWMctzoNwD/bfzGd1DyTnZvWMjyDE3iE1LMt0TlNRDfv6CjM=,iv:lvPvnJkHEIzO7KYKk0dvZf6TCynw9/qmpHHI6pB8hZM=,tag:eydFpX4V3Yb0ySQmoXKtfQ==,type:str]
    pgp:
        - created_at: "2022-04-16T22:10:01Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7+cp4/TBTEzARAAu7xw60NzXa69C89sEkCb4cyFl61XwNQgSTboRw+HIAPQ
            GcsCnsQOnepKq0QW2lzmEw/bkkwySMq93m3HyGY0k+ZXTmGTcFDy+kNS7g5gBwrm
            nW+aWR5lx6A/+rOv3ntYId4IcUP2IqqnY/peqwxc2jQGlIAKSINvi4YNuFTw1g9u
            O/Pgpwpqvip2A4Iu4nEcJYKIps0QUE5miOrniZ3Q5EX+O+O2ZaIngtE/HbIjcXHa
            +NLCUHRhlhiNsqwQn82uKd0gmHFoRufqgYBcWeRG7fDQQTEm5lHqevb3xveJw38L
            O381tiADGUYWHptojI1dCrl8YaHW6F2+uvNDXK738URt7MUlEpKPKouk/bCWTZup
            UHQCc9am5hrjIo5796Ctwz46puQHSwaCizt4QaRO8mFrFWCtkh4c5fw6iw/t5seQ
            SaoQvKSVkdgMI2q8BUEi+UiwX0oqOxdbOICIYiSrpxKCZHcM91ZGfE1d7pDzQ9J0
            7l4yJ3l/ELK/Hs9kkG+RfgYL1Ls84fBswrXidDptg8BMHZY2b7hZdxR8o0jXGI/H
            H1a0VjLSRB5QG339V0MlIap69KuszVJCJuFviXrkwOzYvhxQVSmda76ENpM3znEC
            fGZwfBATijX8byo2WH0x3JhgFB+RoEeKVDVTCJJHq7l+iWgjwv1b52O3Z16bIejU
            aAEJAhCvkKJohHvPSeIwlgfoNjwQRM3Uqm6q0yyAt56+4SwbDh8W3TfQGNFMWWHU
            sIoz5lZbCi8ghnBlGDSpyNdMqDNNOjpeBzI5p9wHF+6Ly6jV8YSBs7wrZXXOhPXd
            X/ZYuMA6EDTy
            =LwVk
            -----END PGP MESSAGE-----
          fp: 0CB42C70DE4BE652338BD2A80558B18F443297CD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
