apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-prod-secrets
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system 
  path: ./clusters/cluster-prod/secrets
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
